from time import sleep

def historia():
    print("inicializando...")
    sleep(1)
    print("~~" * 20)
    print("Carregamento completo!\nBEM VINDO AO <ERROR>")
    print("~~" * 20)
    print("Você acorda")
    print("O céu é escuro, não existem estrelas ou qualquer sutil brilho lunar")
    sleep(1)
    print("Em sua frente existem uma fogueira, duas figuras  se esquentam ao redor dela.")
    print("<homem desconhecido> Parece que ??? acordou.")
    print("<Mulher desconhecida> \nOh, achei que ??? não estava respirando.")
    sleep(5)
    print("Você tenta falar..")
    sleep(1)
    print("O som de sua voz é nulo.")
    sleep(1)
    print("<Homem desconhecido> \nHum, você é uma casca suponho. ")
    print("<Homem desconhecido> \nNão esperava ver uma depois de tanto tempo.")
    print("<Mulher desconhecida> \nO que é uma casca?")
    print("<Homem desconhecido> \nAh, mil perdões, esqueci que você era muito jovem quando elas surgiram.")
    print("<Homem desconhecido> \nUma casca é um receptor de uma consciência exterior, que apenas recebe ordens e não tem de fato controle sobre suas ações.")
    print("<homem desconhecido> \nBom, acho que não tem importância. Cascas são apenas cascas, não espere que ??? responda.")
    sleep(5)
    print("<Mulher desconhecida> \nNós encontramos você nas margens de um rio, então te trouxemos até aqui.")
    print("<Mulher desconhecida> \nMeu nome é Solenvir e esse senhor do nosso lado de chama Carot.")
    sleep(3)
    name = input("Qual seria o seu nome? ")
    print('~~' * 20)
    print(f"<Carot> \n{name} O tempo é curto, lamento em dizer mas você terá que fazer sua escolha.")
    sleep(1)
    print("- O Carote lhe mostra três pergaminho estranhos.")
    sleep(0.5)
    print("<Carot>\nPara simplificar, esse mundo é perigoso para vagar sozinho, então meu objetivo é ceder uma mínima proteção dando o controle de seres inferiores para vocês.")
    print("<Solenvir>\nEu escolherei logo em seguida, estou curiosa pra ver como isso funciona.")
    print("<Os pergaminhos tem escritas em seus parte exterior com nomes que você pode ler>")
    sleep(2)
    return name